server: 
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: aluno
    password: aluno
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
